<?php

# All available TLDs
Configure::set('Srsx.tlds', array(
    ".ac.id",
    ".biz.id",
    ".co.id",
    ".id",
    ".my.id",
    ".or.id",
    ".ponpes.id",
    ".sch.id",
    ".web.id",
    ".ac",
    ".academy",
    ".accountant",
    ".accountants",
    ".actor",
    ".agency",
    ".airforce",
    ".apartments",
    ".archi",
    ".army",
    ".art",
    ".asia",
    ".associates",
    ".attorney",
    ".auction",
    ".audio",
    ".auto",
    ".autos",
    ".band",
    ".bar",
    ".bargains",
    ".beer",
    ".bible",
    ".bid",
    ".bike",
    ".bingo",
    ".bio",
    ".biz",
    ".black",
    ".blackfriday",
    ".blue",
    ".boats",
    ".boston",
    ".boutique",
    ".builders",
    ".business",
    ".cab",
    ".cafe",
    ".camera",
    ".camp",
    ".capital",
    ".cards",
    ".care",
    ".careers",
    ".cars",
    ".casa",
    ".cash",
    ".casino",
    ".catering",
    ".cc",
    ".center",
    ".charity",
    ".chat",
    ".cheap",
    ".christmas",
    ".church",
    ".city",
    ".claims",
    ".cleaning",
    ".click",
    ".clinic",
    ".clothing",
    ".cloud",
    ".club",
    ".coach",
    ".codes",
    ".coffee",
    ".college",
    ".com",
    ".com.lb2",
    ".community",
    ".company",
    ".computer",
    ".condos",
    ".construction",
    ".consulting",
    ".contractors",
    ".cooking",
    ".cool",
    ".country",
    ".coupons",
    ".credit",
    ".creditcard",
    ".cricket",
    ".cruises",
    ".cx",
    ".dance",
    ".date",
    ".dating",
    ".deals",
    ".degree",
    ".delivery",
    ".democrat",
    ".dental",
    ".dentist",
    ".design",
    ".diamonds",
    ".diet",
    ".digital",
    ".direct",
    ".directory",
    ".discount",
    ".dog",
    ".domains",
    ".download",
    ".eco",
    ".education",
    ".email",
    ".energy",
    ".engineer",
    ".engineering",
    ".enterprises",
    ".equipment",
    ".estate",
    ".eu",
    ".events",
    ".exchange",
    ".expert",
    ".exposed",
    ".express",
    ".fail",
    ".faith",
    ".family",
    ".fan",
    ".fans",
    ".farm",
    ".fashion",
    ".feedback",
    ".finance",
    ".financial",
    ".fish",
    ".fishing",
    ".fit",
    ".fitness",
    ".flights",
    ".florist",
    ".flowers",
    ".fm",
    ".football",
    ".forsale",
    ".foundation",
    ".fun",
    ".fund",
    ".furniture",
    ".futbol",
    ".fyi",
    ".gallery",
    ".games",
    ".garden",
    ".gift",
    ".gifts",
    ".gives",
    ".glass",
    ".global",
    ".gmbh",
    ".gold",
    ".golf",
    ".graphics",
    ".gratis",
    ".green",
    ".gripe",
    ".group",
    ".guide",
    ".guitars",
    ".guru",
    ".haus",
    ".healthcare",
    ".help",
    ".hiphop",
    ".hiv",
    ".hockey",
    ".holdings",
    ".holiday",
    ".homes",
    ".horse",
    ".hospital",
    ".host",
    ".hosting",
    ".house",
    ".icu",
    ".immo",
    ".immobilien",
    ".industries",
    ".info",
    ".ink",
    ".institute",
    ".insure",
    ".international",
    ".investments",
    ".io",
    ".jetzt",
    ".jewelry",
    ".juegos",
    ".kaufen",
    ".kim",
    ".kitchen",
    ".la",
    ".land",
    ".lawyer",
    ".lease",
    ".legal",
    ".life",
    ".lighting",
    ".limited",
    ".limo",
    ".link",
    ".live",
    ".loan",
    ".loans",
    ".lol",
    ".love",
    ".ltd",
    ".maison",
    ".management",
    ".market",
    ".marketing",
    ".mba",
    ".me",
    ".media",
    ".memorial",
    ".men",
    ".miami",
    ".moda",
    ".mom",
    ".money",
    ".mortgage",
    ".motorcycles",
    ".movie",
    ".name",
    ".navy",
    ".net",
    ".network",
    ".news",
    ".ninja",
    ".observer",
    ".online",
    ".ooo",
    ".org",
    ".organic",
    ".partners",
    ".parts",
    ".party",
    ".pet",
    ".photo",
    ".photography",
    ".photos",
    ".pics",
    ".pictures",
    ".pink",
    ".pizza",
    ".place",
    ".plumbing",
    ".plus",
    ".press",
    ".pro",
    ".productions",
    ".promo",
    ".properties",
    ".property",
    ".protection",
    ".pub",
    ".pw",
    ".racing",
    ".radio.am",
    ".radio.fm",
    ".realty",
    ".recipes",
    ".red",
    ".rehab",
    ".reise",
    ".reisen",
    ".reit",
    ".rent",
    ".rentals",
    ".repair",
    ".report",
    ".republican",
    ".rest",
    ".restaurant",
    ".review",
    ".reviews",
    ".rip",
    ".rocks",
    ".rodeo",
    ".run",
    ".sale",
    ".salon",
    ".sarl",
    ".school",
    ".schule",
    ".science",
    ".security",
    ".services",
    ".sexy",
    ".sh",
    ".shiksha",
    ".shoes",
    ".shop",
    ".shopping",
    ".show",
    ".singles",
    ".site",
    ".ski",
    ".soccer",
    ".social",
    ".software",
    ".solar",
    ".solutions",
    ".space",
    ".storage",
    ".store",
    ".stream",
    ".studio",
    ".style",
    ".supplies",
    ".supply",
    ".support",
    ".surf",
    ".surgery",
    ".systems",
    ".tattoo",
    ".tax",
    ".taxi",
    ".team",
    ".tech",
    ".technology",
    ".tennis",
    ".theater",
    ".theatre",
    ".tickets",
    ".tienda",
    ".tips",
    ".tires",
    ".today",
    ".tools",
    ".top",
    ".tours",
    ".town",
    ".toys",
    ".trade",
    ".training",
    ".tv",
    ".university",
    ".uno",
    ".vacations",
    ".ventures",
    ".vet",
    ".viajes",
    ".video",
    ".villas",
    ".vin",
    ".vip",
    ".vision",
    ".vodka",
    ".voyage",
    ".watch",
    ".webcam",
    ".website",
    ".wedding",
    ".wiki",
    ".win",
    ".wine",
    ".work",
    ".works",
    ".world",
    ".wtf",
    ".xyz",
    ".yachts",
    ".yoga",
    ".zone",
));

# Transfer fields
Configure::set('Srsx.transfer_fields', array(
    'domain-name' => array(
        'label' => Language::_('Srsx.transfer.domain-name', true),
        'type' => 'text',
    ),
    'epp-code' => array(
        'label' => Language::_('Srsx.transfer.epp-code', true),
        'type' => 'text',
    ),
));

# Domain fields
Configure::set('Srsx.domain_fields', array(
    'domain-name' => array(
        'label' => Language::_('Srsx.domain.domain-name', true),
        'type' => 'text',
    ),
));

# Nameserver fields
Configure::set('Srsx.nameserver_fields', array(
    'ns1' => array(
        'label' => Language::_('Srsx.nameserver.ns1', true),
        'type' => 'text',
    ),
    'ns2' => array(
        'label' => Language::_('Srsx.nameserver.ns2', true),
        'type' => 'text',
    ),
    'ns3' => array(
        'label' => Language::_('Srsx.nameserver.ns3', true),
        'type' => 'text',
    ),
    'ns4' => array(
        'label' => Language::_('Srsx.nameserver.ns4', true),
        'type' => 'text',
    ),
));

# Contact fields
Configure::set('Srsx.contact_fields', array(
    'contactid' => array(
        'label' => Language::_('Srsx.contact.contactid', true),
        'type' => 'text',
    ),
    'email' => array(
        'label' => Language::_('Srsx.contact.email', true),
        'type' => 'text',
    ),
    'fname' => array(
        'label' => Language::_('Srsx.contact.fname', true),
        'type' => 'text',
    ),
    'lname' => array(
        'label' => Language::_('Srsx.contact.lname', true),
        'type' => 'text',
    ),
    'company' => array(
        'label' => Language::_('Srsx.contact.company', true),
        'type' => 'text',
    ),
    'address' => array(
        'label' => Language::_('Srsx.contact.address', true),
        'type' => 'text',
    ),
    'address2' => array(
        'label' => Language::_('Srsx.contact.address2', true),
        'type' => 'text',
    ),
    'address3' => array(
        'label' => Language::_('Srsx.contact.address3', true),
        'type' => 'text',
    ),
    'city' => array(
        'label' => Language::_('Srsx.contact.city', true),
        'type' => 'text',
    ),
    'state' => array(
        'label' => Language::_('Srsx.contact.state', true),
        'type' => 'text',
    ),
    'phonenumber' => array(
        'label' => Language::_('Srsx.contact.phonenumber', true),
        'type' => 'text',
    ),
    'fax' => array(
        'label' => Language::_('Srsx.contact.fax', true),
        'type' => 'text',
    ),
    'country' => array(
        'label' => Language::_('Srsx.contact.country', true),
        'type' => 'text',
    ),
    'postcode' => array(
        'label' => Language::_('Srsx.contact.postcode', true),
        'type' => 'text',
    ),
));
